name: Feature Request
about: Propose an enhancement to quality, safety, or operations
labels: [enhancement]
title: "[FEATURE] "
body:
  - type: checkboxes
    id: language_confirmation
    attributes:
      label: Language
      options:
        - label: I confirm this issue is written in English.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Which operational or quality gap should be closed? Please write in English.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Include acceptance criteria and rollout constraints. Please write in English.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Expected effect on false positives, latency, and ops. Please write in English.
