name: Ops Task
about: Track deployment, reliability, or maintenance work
labels: [operations]
title: "[OPS] "
body:
  - type: checkboxes
    id: language_confirmation
    attributes:
      label: Language
      options:
        - label: I confirm this issue is written in English.
          required: true
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Please write in English.
    validations:
      required: true
  - type: textarea
    id: checklist
    attributes:
      label: Execution Checklist
      description: Add concrete tasks and validation criteria. Please write in English.
    validations:
      required: true
  - type: input
    id: owner
    attributes:
      label: Responsible Owner
