name: quality-gate

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: quality-gate-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: MDSoftware-DE/.github/.github/workflows/quality-gate-reusable.yml@main
    with:
      node_version: "20"
      run_lint: true
      run_tests: true
      run_build: true
      run_smoke: false
      fail_if_no_checks: false
